config:
  yourlsserver: http://nerderrhe.in
  yourlssig: secret_key
  server: irc.freenode.org
  nick: nerdbot
  password: nick_password
  record_file: /var/cache/record.dat
  seen_file: /var/cache/seenlog.dat
